### ISSUE TITLE
Config files to test ACLs

### ISSUE THREAD

**Issue by cpretzer** [mmiller1/weird-linkerd-squid-repro#1]
Here are the modified squid Deployment and ConfigMap resources that I used to modify the squid ACLs.

Just wanted to share these files quickly without having to fork the repo and submit a PR :)

`squid.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    run: squid
  name: squid
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    run: squid
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: squid
  name: squid
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: squid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: squid
    spec:
      containers:
      - image: scbunn/squid:latest
        imagePullPolicy: Always
        name: squid
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: squid-conf
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: squid-conf
        configMap:
          name: squid-config
          items:
          - key: squid.conf
            path: squid.conf
```

`squid-cm.yml`
```yaml
apiVersion: v1
data:
  squid.conf: |
    # ----------------------------------------------------------------------------
    # Basic squid configuration
    # ----------------------------------------------------------------------------

    # common settings
    # ---------------
    http_port 3128
    cache_effective_user squid
    cache_effective_group squid
    workers 1
    debug_options ALL,9

    # Standard ACL configuration
    # --------------------------

    # Allow proxing standard web traffic only
    acl SSL_ports port 443
    acl SSL_ports port 3128
    acl Safe_ports port 80
    acl Safe_ports port 443
    acl Safe_ports port 3128
    acl CONNECT method CONNECT

    # ACLs to target for logging
    acl success_codes http_status 100-199 # informational
    acl success_codes http_status 200-299 # successful transactions
    acl success_codes http_status 300-399 # redirection
    acl failure_codes http_status 400-499 # client error
    acl failure_codes http_status 500-599 # server error
    acl success_hier hier_code HIER_DIRECT
    acl failure_hier hier_code HIER_NONE
    acl failure all-of CONNECT failure_hier
    acl failure all-of !CONNECT failure_codes
    acl success all-of CONNECT success_hier
    acl success all-of !CONNECT success_codes

    # ACL operators
    # -------------
    http_access allow localhost
    http_access deny to_localhost
    http_access deny CONNECT !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access deny !Safe_ports
    http_access allow Safe_ports
    http_access deny all

    # Logging configuration
    # ---------------------
    log_mime_hdrs on
    access_log daemon:/var/log/squid/access.log squid !success
    cache_log /var/log/squid/cache.log
kind: ConfigMap
metadata:
  name: squid-config
  namespace: default
```
